import { test } from './_boot.test';

export default test('ts/unit/qunit.Assert', (assert) => {

  /*
  const engine = new Engine()
  const assertions: IAssertion[] = []
  const testMock: ITest = { category: "", name: "", run: () => {} }
  const reportMock = { assertions: assertions, startDate: new Date(), elapsedMilliseconds:0 }
  const assertMock = new Assert(engine, testMock, reportMock)

  function lastAssertion() {
    return assertions[assertions.length - 1];
  }

  function assertLastSuccess() {
    assert(lastAssertion().type === SUCCESS)
  }

  function assertLastFailure() {
    assert(lastAssertion().type === FAILURE)
  }

  //ok()
  assertMock.ok(true)
  assertLastSuccess()

  assertMock.ok(false)
  assertLastFailure()

  //strictEquals()
  assertMock.strictEqual(null, null)
  assertLastSuccess()

  assertMock.strictEqual(undefined, null)
  assertLastFailure()

  assertMock.strictEqual(1, 1)
  assertLastSuccess()

  assertMock.strictEqual<any>("1", 1)
  assertLastFailure()

  assertMock.strictEqual(NaN, NaN)
  assertLastSuccess()

  //equals()
  assertMock.equal(null, null)
  assertLastSuccess()

  assertMock.equal(undefined, null)
  assertLastSuccess()

  assertMock.equal(1, 1)
  assertLastSuccess()

  assertMock.equal<any>("1", 1)
  assertLastSuccess()

  assertMock.equal(NaN, NaN)
  assertLastSuccess()

  //throws()
  assertMock.throws(() => {})
  assertLastFailure()

  assertMock.throws(() => { throw new TypeError() })
  assertLastSuccess()

  assertMock.throws(() => { throw new TypeError() }, TypeError)
  assertLastSuccess()

  assertMock.throws(() => { throw new TypeError() }, Error)
  assertLastSuccess()

  assertMock.throws(() => { throw new Error() }, TypeError)
  assertLastFailure()

  assertMock.throws(() => { throw new Error("blah") }, "Error: blah")
  assertLastSuccess()

  assertMock.throws(() => { throw new TypeError("blah") }, "TypeError: blah")
  assertLastSuccess()

  assertMock.throws(() => { throw new Error("foo") }, "Error: blah")
  assertLastFailure()
  */
});
